name: Lint Files

on:
  issue_comment:
    types: [created]

jobs:
  lint-files:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: khan/pull-request-comment-trigger@master
      id: lint
      with:
        trigger: '/lint'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
      if: steps.lint.outputs.triggered == 'true'

    - name: Install sqlfluff
      run: pip install sqlfluff
      if: steps.lint.outputs.triggered == 'true'

    - uses: xt0rted/pull-request-comment-branch@v1
      id: comment-branch
      if: steps.lint.outputs.triggered == 'true'

    - run: git checkout ${{ steps.comment-branch.outputs.head_ref }}
      if: steps.lint.outputs.triggered == 'true'

    - name: Lint files
      run: |
        touch output.txt
        echo "```" >> output.txt
        diff-quality --violations sqlfluff --compare-branch remotes/origin/main >> output.txt
        echo "```" >> output.txt
      if: steps.lint.outputs.triggered == 'true'

    - name: Send Comment
      uses: maxkomarychev/octions/octions/issues/create-comment@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue_number: ${{ github.event.issue.number }}
        body: FILE::output.txt
      if: hashFiles('output.txt') != ''
